import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../core/utils/file_helper.dart';
import '../../core/utils/gallery_saver.dart';
import 'voucher_model.dart';

enum WhatsAppLaunchStatus {
  success,
  noPhoneNumber,
  notInstalled,
  error,
}

class VoucherService {
  /// Generates human-friendly, formatted WhatsApp text for the transaction memo.
  static String generateTextReceipt(VoucherData data, {bool isBengali = true}) {
    final isBaki = data.transaction.isBaki;
    final currency = data.settings.currencySymbol;

    String formatMoney(double amount) {
      final fmt = (amount.abs() % 1 == 0)
          ? NumberFormat('#,##0')
          : NumberFormat('#,##0.00');
      final formatted = fmt.format(amount.abs());
      return isBengali ? PhoneUtils.toBengaliNumber(formatted) : formatted;
    }

    String formatDate(DateTime dt) {
      final local = dt.toLocal();
      final fmt = DateFormat('dd MMM yyyy, hh:mm a');
      final formatted = fmt.format(local);
      return isBengali ? PhoneUtils.toBengaliNumber(formatted) : formatted;
    }

    final buffer = StringBuffer();
    final shopName = data.settings.shopName.trim().isEmpty
        ? 'My Shop'
        : data.settings.shopName.trim();
    buffer.writeln('🏪 *$shopName*');

    final address = data.settings.shopAddress?.trim();
    final phone = data.settings.shopPhone?.trim();
    if (address != null && address.isNotEmpty) {
      buffer.write('📍 $address');
    }
    if (phone != null && phone.isNotEmpty) {
      if (address != null && address.isNotEmpty) buffer.write(' | ');
      buffer.write('📞 $phone');
    }
    if ((address != null && address.isNotEmpty) || (phone != null && phone.isNotEmpty)) {
      buffer.writeln();
    }

    buffer.writeln('─────────────────────────');
    final title = isBaki
        ? (isBengali ? 'বাকি চালান' : 'CREDIT MEMO')
        : (isBengali ? 'জমা রসিদ' : 'PAYMENT RECEIPT');
    buffer.writeln('🧾 *$title:* ${data.voucherNumber}');
    buffer.writeln('👤 *${isBengali ? "কাস্টমার" : "Customer"}:* ${data.customer.name}');
    buffer.writeln('📅 *${isBengali ? "তারিখ" : "Date"}:* ${formatDate(data.transaction.date)}');
    buffer.writeln('─────────────────────────');

    if (data.items.isNotEmpty) {
      buffer.writeln(isBengali ? '🛒 *পণ্য ও বিবরণ:*' : '🛒 *Items:*');
      for (int i = 0; i < data.items.length; i++) {
        final item = data.items[i];
        final qtyStr = item.quantity != null && item.quantity!.isNotEmpty
            ? ' (${item.quantity})'
            : '';
        buffer.writeln('• ${item.name}$qtyStr: $currency ${formatMoney(item.total)}');
      }
      buffer.writeln();
    } else if (data.notes != null && data.notes!.trim().isNotEmpty) {
      buffer.writeln('📝 *${isBengali ? "নোট" : "Note"}:* ${data.notes!.trim()}');
      buffer.writeln();
    }

    final txLabel = isBaki
        ? (isBengali ? 'এই চালানের পরিমাণ:' : 'Current Credit:')
        : (isBengali ? 'জমা দেওয়ার পরিমাণ:' : 'Current Payment:');
    final sign = isBaki ? '+' : '-';
    buffer.writeln('💵 *$txLabel* $sign$currency ${formatMoney(data.balance.transactionAmount)}');

    final prevLabel = isBengali ? 'পূর্বের বাকি:' : 'Previous Due:';
    buffer.writeln('📊 *$prevLabel* $currency ${formatMoney(data.balance.balanceBefore)}');

    if (data.balance.balanceAfter > 0) {
      final totalLabel = isBengali ? 'বর্তমান মোট বাকি:' : 'Total Net Due:';
      buffer.writeln('🔴 *$totalLabel $currency ${formatMoney(data.balance.balanceAfter)}*');
    } else {
      buffer.writeln('🟢 *${isBengali ? "হিসাব পরিশোধিত" : "Fully Settled"}*');
    }

    buffer.writeln('─────────────────────────');
    buffer.writeln(isBengali
        ? 'ধন্যবাদ! বাকি পরিশোধ করে আমাদের পাশে থাকুন।'
        : 'Thank you for your business!');
    buffer.write(isBengali
        ? '_বাকি খাতা অ্যাপের মাধ্যমে তৈরি_'
        : '_Generated by Baki Khata App_');

    return buffer.toString();
  }

  /// Captures a RenderRepaintBoundary widget as a high-resolution PNG byte buffer.
  static Future<Uint8List?> captureWidgetPng(GlobalKey repaintKey, {double pixelRatio = 3.0}) async {
    try {
      final boundary = repaintKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) return null;

      final ui.Image image = await boundary.toImage(pixelRatio: pixelRatio);
      final ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      return byteData?.buffer.asUint8List();
    } catch (e) {
      debugPrint('[VoucherService] Failed to capture widget PNG: $e');
      return null;
    }
  }

  /// Directly opens WhatsApp with the customer's chat inbox open and voucher text pre-filled.
  static Future<WhatsAppLaunchStatus> openWhatsAppDirectChat({
    required VoucherData data,
    bool isBengali = true,
  }) async {
    final phone = data.customer.phone;
    final normPhone = PhoneUtils.normalizeForWhatsApp(phone);
    if (normPhone == null) {
      return WhatsAppLaunchStatus.noPhoneNumber;
    }

    final text = generateTextReceipt(data, isBengali: isBengali);
    final encoded = Uri.encodeComponent(text);

    // Direct WhatsApp scheme (fastest, directly opens into WhatsApp app)
    final directWaUri = Uri.parse('whatsapp://send?phone=$normPhone&text=$encoded');
    // Universal wa.me link (standard fallback)
    final universalWaUri = Uri.parse('https://wa.me/$normPhone?text=$encoded');

    try {
      if (await canLaunchUrl(directWaUri)) {
        final launched = await launchUrl(directWaUri, mode: LaunchMode.externalApplication);
        if (launched) return WhatsAppLaunchStatus.success;
      }

      if (await canLaunchUrl(universalWaUri)) {
        final launched = await launchUrl(universalWaUri, mode: LaunchMode.externalApplication);
        if (launched) return WhatsAppLaunchStatus.success;
      }

      return WhatsAppLaunchStatus.notInstalled;
    } catch (e) {
      debugPrint('[VoucherService] Failed to launch WhatsApp: $e');
      return WhatsAppLaunchStatus.error;
    }
  }

  /// Saves the rendered voucher image directly to the device's public photo gallery using GallerySaver.
  static Future<bool> saveVoucherToGallery({
    required GlobalKey repaintKey,
    required VoucherData data,
  }) async {
    final bytes = await captureWidgetPng(repaintKey);
    if (bytes == null) return false;

    try {
      final sanitizedId = data.voucherNumber.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
      final fileName = 'voucher_${sanitizedId}_${DateTime.now().millisecondsSinceEpoch}';
      return await GallerySaver.saveImageBytes(bytes, name: fileName);
    } catch (e) {
      debugPrint('[VoucherService] Failed to save image to gallery: $e');
      return false;
    }
  }

  /// Sends the formatted voucher text directly to the customer on WhatsApp via wa.me URL (Legacy/Compatibility).
  static Future<bool> sendWhatsAppText(
    BuildContext context,
    VoucherData data, {
    bool isBengali = true,
  }) async {
    final status = await openWhatsAppDirectChat(data: data, isBengali: isBengali);
    if (status == WhatsAppLaunchStatus.success) return true;

    // Fallback: If phone not found or WhatsApp failed, share text via system share sheet
    final text = generateTextReceipt(data, isBengali: isBengali);
    final result = await Share.share(
      text,
      subject: '${data.settings.shopName} - ${data.voucherNumber}',
    );
    return result.status == ShareResultStatus.success;
  }

  /// Captures the voucher image and shares it via Share.shareXFiles (universal system share sheet).
  static Future<bool> shareVoucherImage({
    required GlobalKey repaintKey,
    required VoucherData data,
    bool isBengali = true,
  }) async {
    final bytes = await captureWidgetPng(repaintKey);
    if (bytes == null) return false;

    try {
      final sanitizedId = data.voucherNumber.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
      final summary = generateTextReceipt(data, isBengali: isBengali);
      final xFile = XFile.fromData(
        bytes,
        mimeType: 'image/png',
        name: 'voucher_$sanitizedId.png',
      );

      final result = await Share.shareXFiles(
        [xFile],
        text: summary,
        subject: '${data.settings.shopName} - ${data.voucherNumber}',
      );
      return result.status == ShareResultStatus.success;
    } catch (e) {
      debugPrint('[VoucherService] Failed to share voucher image: $e');
      return false;
    }
  }

  /// Saves the voucher image to device storage and presents the user with save/export options (Legacy/Compatibility).
  static Future<String?> saveVoucherImageToDevice({
    required GlobalKey repaintKey,
    required VoucherData data,
  }) async {
    final bytes = await captureWidgetPng(repaintKey);
    if (bytes == null) return null;

    try {
      final sanitizedId = data.voucherNumber.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
      return await saveFileToDisk(bytes, 'voucher_$sanitizedId.png');
    } catch (e) {
      debugPrint('[VoucherService] Failed to save voucher image: $e');
      return null;
    }
  }
}
