import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import 'voucher_model.dart';

class VoucherService {
  /// Generates human-friendly, formatted WhatsApp text for the transaction memo.
  static String generateTextReceipt(VoucherData data, {bool isBengali = true}) {
    final isBaki = data.transaction.isBaki;
    final currency = data.settings.currencySymbol;

    String formatMoney(double amount) {
      final fmt = (amount.abs() % 1 == 0)
          ? NumberFormat('#,##0')
          : NumberFormat('#,##0.00');
      final formatted = fmt.format(amount.abs());
      return isBengali ? PhoneUtils.toBengaliNumber(formatted) : formatted;
    }

    String formatDate(DateTime dt) {
      final local = dt.toLocal();
      final fmt = DateFormat('dd MMM yyyy, hh:mm a');
      final formatted = fmt.format(local);
      return isBengali ? PhoneUtils.toBengaliNumber(formatted) : formatted;
    }

    final buffer = StringBuffer();
    final shopName = data.settings.shopName.trim().isEmpty
        ? 'My Shop'
        : data.settings.shopName.trim();
    buffer.writeln('🏪 *$shopName*');

    final address = data.settings.shopAddress?.trim();
    final phone = data.settings.shopPhone?.trim();
    if (address != null && address.isNotEmpty) {
      buffer.write('📍 $address');
    }
    if (phone != null && phone.isNotEmpty) {
      if (address != null && address.isNotEmpty) buffer.write(' | ');
      buffer.write('📞 $phone');
    }
    if ((address != null && address.isNotEmpty) || (phone != null && phone.isNotEmpty)) {
      buffer.writeln();
    }

    buffer.writeln('─────────────────────────');
    final title = isBaki
        ? (isBengali ? 'বাকি চালান' : 'CREDIT MEMO')
        : (isBengali ? 'জমা রসিদ' : 'PAYMENT RECEIPT');
    buffer.writeln('🧾 *$title:* ${data.voucherNumber}');
    buffer.writeln('👤 *${isBengali ? "কাস্টমার" : "Customer"}:* ${data.customer.name}');
    buffer.writeln('📅 *${isBengali ? "তারিখ" : "Date"}:* ${formatDate(data.transaction.date)}');
    buffer.writeln('─────────────────────────');

    if (data.items.isNotEmpty) {
      buffer.writeln(isBengali ? '🛒 *পণ্য ও বিবরণ:*' : '🛒 *Items:*');
      for (int i = 0; i < data.items.length; i++) {
        final item = data.items[i];
        final qtyStr = item.quantity != null && item.quantity!.isNotEmpty
            ? ' (${item.quantity})'
            : '';
        buffer.writeln('• ${item.name}$qtyStr: $currency ${formatMoney(item.total)}');
      }
      buffer.writeln();
    } else if (data.notes != null && data.notes!.trim().isNotEmpty) {
      buffer.writeln('📝 *${isBengali ? "নোট" : "Note"}:* ${data.notes!.trim()}');
      buffer.writeln();
    }

    final txLabel = isBaki
        ? (isBengali ? 'এই চালানের পরিমাণ:' : 'Current Credit:')
        : (isBengali ? 'জমা দেওয়ার পরিমাণ:' : 'Current Payment:');
    final sign = isBaki ? '+' : '-';
    buffer.writeln('💵 *$txLabel* $sign$currency ${formatMoney(data.balance.transactionAmount)}');

    final prevLabel = isBengali ? 'পূর্বের বাকি:' : 'Previous Due:';
    buffer.writeln('📊 *$prevLabel* $currency ${formatMoney(data.balance.balanceBefore)}');

    if (data.balance.balanceAfter > 0) {
      final totalLabel = isBengali ? 'বর্তমান মোট বাকি:' : 'Total Net Due:';
      buffer.writeln('🔴 *$totalLabel $currency ${formatMoney(data.balance.balanceAfter)}*');
    } else {
      buffer.writeln('🟢 *${isBengali ? "হিসাব পরিশোধিত" : "Fully Settled"}*');
    }

    buffer.writeln('─────────────────────────');
    buffer.writeln(isBengali
        ? 'ধন্যবাদ! বাকি পরিশোধ করে আমাদের পাশে থাকুন।'
        : 'Thank you for your business!');
    buffer.write(isBengali
        ? '_বাকি খাতা অ্যাপের মাধ্যমে তৈরি_'
        : '_Generated by Baki Khata App_');

    return buffer.toString();
  }

  /// Captures a RenderRepaintBoundary widget as a high-resolution PNG byte buffer.
  static Future<Uint8List?> captureWidgetPng(GlobalKey repaintKey, {double pixelRatio = 3.0}) async {
    try {
      final boundary = repaintKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) return null;

      final ui.Image image = await boundary.toImage(pixelRatio: pixelRatio);
      final ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      return byteData?.buffer.asUint8List();
    } catch (e) {
      debugPrint('[VoucherService] Failed to capture widget PNG: $e');
      return null;
    }
  }

  /// Sends the formatted voucher text directly to the customer on WhatsApp via wa.me URL.
  static Future<bool> sendWhatsAppText(
    BuildContext context,
    VoucherData data, {
    bool isBengali = true,
  }) async {
    final text = generateTextReceipt(data, isBengali: isBengali);
    final normPhone = PhoneUtils.normalizeForWhatsApp(data.customer.phone);

    if (normPhone != null) {
      final encoded = Uri.encodeComponent(text);
      final waUri = Uri.parse('https://wa.me/$normPhone?text=$encoded');
      try {
        if (await canLaunchUrl(waUri)) {
          return await launchUrl(waUri, mode: LaunchMode.externalApplication);
        }
      } catch (e) {
        debugPrint('[VoucherService] Could not launch wa.me: $e');
      }
    }

    // Fallback: If phone not found or wa.me failed, share text via system share sheet
    final result = await Share.share(
      text,
      subject: '${data.settings.shopName} - ${data.voucherNumber}',
    );
    return result.status == ShareResultStatus.success;
  }

  /// Captures the voucher image and shares it via Share.shareXFiles (which allows sending to WhatsApp).
  static Future<bool> shareVoucherImage({
    required GlobalKey repaintKey,
    required VoucherData data,
    bool isBengali = true,
  }) async {
    final bytes = await captureWidgetPng(repaintKey);
    if (bytes == null) return false;

    try {
      final tempDir = await getTemporaryDirectory();
      final sanitizedId = data.voucherNumber.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
      final filePath = '${tempDir.path}/voucher_$sanitizedId.png';
      final file = File(filePath);
      await file.writeAsBytes(bytes);

      final summary = generateTextReceipt(data, isBengali: isBengali);
      final xFile = XFile(file.path, mimeType: 'image/png', name: 'voucher_$sanitizedId.png');

      final result = await Share.shareXFiles(
        [xFile],
        text: summary,
        subject: '${data.settings.shopName} - ${data.voucherNumber}',
      );
      return result.status == ShareResultStatus.success;
    } catch (e) {
      debugPrint('[VoucherService] Failed to share voucher image: $e');
      return false;
    }
  }

  /// Saves the voucher image to device cache and presents the user with save/export options.
  static Future<String?> saveVoucherImageToDevice({
    required GlobalKey repaintKey,
    required VoucherData data,
  }) async {
    final bytes = await captureWidgetPng(repaintKey);
    if (bytes == null) return null;

    try {
      final dir = await getApplicationDocumentsDirectory();
      final sanitizedId = data.voucherNumber.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
      final filePath = '${dir.path}/voucher_$sanitizedId.png';
      final file = File(filePath);
      await file.writeAsBytes(bytes);
      return filePath;
    } catch (e) {
      debugPrint('[VoucherService] Failed to save voucher image: $e');
      return null;
    }
  }
}
